export const skills = [
    {
        id: 1,
        name: 'python',
        proficiency: '70%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
    },
    {
        id: 2,
        name: 'javascript',
        proficiency: '75%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
    },
    {
        id: 3,
        name: 'java',
        proficiency: '30%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
    },
    {
        id: 4,
        name: 'django',
        proficiency: '80%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain-wordmark.svg',
    },
    {
        id: 5,
        name: 'html',
        proficiency: '85%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg',
    },
    {
        id: 6,
        name: 'css',
        proficiency: '85%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg',
    },
    {
        id: 7,
        name: 'next',
        proficiency: '35%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
    },
    {
        id: 8,
        name: 'tailwindcss',
        proficiency: '65%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg',
    },
    {
        id: 9,
        name: 'mongodb',
        proficiency: '25%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg',
    },
    {
        id: 10,
        name: 'express',
        proficiency: '40%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg',
    },
    {
        id: 11,
        name: 'react',
        proficiency: '85%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
    },
    {
        id: 12,
        name: 'node',
        proficiency: '45%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
    },
    {
        id: 13,
        name: 'flask',
        proficiency: '50%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg',
    },
    {
        id: 14,
        name: 'postgresql',
        proficiency: '20%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
    },
    {
        id: 15,
        name: 'cloud platform',
        proficiency: '35%',
        icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg',
    },
]
